src/i_am_vulnerable/bad_sql_practices/urls.py
from django.urls import path

from . import views

app_name = "bad_sql"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.result, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

src/i_am_vulnerable/config/urls.py
"""i_am_vulnerable URL Configuration."""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("bad_sql_practices.urls")),
    path("admin/", admin.site.urls),
]

src/i_am_vulnerable/bad_sql_practices/models.py
from django.db import models


class Question(models.Model):
    question_text: models.CharField = models.CharField(max_length=200)
    pub_date: models.DateTimeField = models.DateTimeField("date published")

    def __str__(self):
        """Returns a formatted string representation."""
        return f"{self.question_text} - [{', '.join(choice.choice_text for choice in self.choice_set.all())}]"


class Choice(models.Model):
    question: models.ForeignKey = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text: models.CharField = models.CharField(max_length=200)
    votes: models.IntegerField = models.IntegerField(default=0)

    def __str__(self):
        """Returns a formatted string representation."""
        return f"{self.question.question_text} - {self.choice_text}"


class Vote(models.Model):
    question: models.ForeignKey = models.ForeignKey(Question, on_delete=models.CASCADE)
    email: models.TextField = models.TextField()

    def __str__(self):
        """Returns a formatted string representation."""
        return f"{self.email} - {self.question.question_text}"

src/i_am_vulnerable/bad_sql_practices/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice, Vote


class IndexView(generic.ListView):
    template_name = "index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


def result(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    choice = get_object_or_404(Choice, pk=request.POST["choice"])
    choice_question = choice.question
    q = get_object_or_404(Question, pk=question_id)
    if choice_question != q:
        return render(
            request,
            "polls/detail.html",
            {
                "question": q,
                "error_message": "You didn't select a valid choice.",
            },
        )
    choice.votes += 1
    choice.save()
    vote = Vote(email=request.POST["email"], question=q)
    vote.save()
    return HttpResponseRedirect(reverse("bad_sql:results", args=(question_id,)))

src/i_am_vulnerable/bad_sql_practices/templates/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'bad_sql:detail' question.id %}">{{ question.question_text }}</a>
            -
            <a href="{% url 'bad_sql:results' question.id %}">See Results</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

src/i_am_vulnerable/bad_sql_practices/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'bad_sql:vote' question.id %}" method="post">
{% csrf_token %}
<label for="email">E-Mail: </label>
<input type="text" name="email" id="email"><br>
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

src/i_am_vulnerable/bad_sql_practices/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'bad_sql:detail' question.id %}">Vote again?</a>
<br>
<a href="{% url 'bad_sql:index' %}">Back to Polls</a>
<br>
The following people have voted:
<ul>
{% for vote in question.vote_set.all %}
    <li>{{ vote.email }}</li>
{% endfor %}
</ul>